#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-json4s
Version  : 3.5.3
Release  : 2
URL      : https://github.com/json4s/json4s/archive/v3.5.3.tar.gz
Source0  : https://github.com/json4s/json4s/archive/v3.5.3.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/json4s/json4s-ast_2.12/3.5.3/json4s-ast_2.12-3.5.3.jar
Source2  : https://repo.maven.apache.org/maven2/org/json4s/json4s-ast_2.12/3.5.3/json4s-ast_2.12-3.5.3.pom
Source3  : https://repo.maven.apache.org/maven2/org/json4s/json4s-core_2.12/3.5.3/json4s-core_2.12-3.5.3.jar
Source4  : https://repo.maven.apache.org/maven2/org/json4s/json4s-core_2.12/3.5.3/json4s-core_2.12-3.5.3.pom
Source5  : https://repo.maven.apache.org/maven2/org/json4s/json4s-jackson_2.12/3.5.3/json4s-jackson_2.12-3.5.3.jar
Source6  : https://repo.maven.apache.org/maven2/org/json4s/json4s-jackson_2.12/3.5.3/json4s-jackson_2.12-3.5.3.pom
Source7  : https://repo.maven.apache.org/maven2/org/json4s/json4s-scalap_2.12/3.5.3/json4s-scalap_2.12-3.5.3.jar
Source8  : https://repo.maven.apache.org/maven2/org/json4s/json4s-scalap_2.12/3.5.3/json4s-scalap_2.12-3.5.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-json4s-data = %{version}-%{release}

%description
# JSON4S [![Build Status](https://travis-ci.org/json4s/json4s.svg?branch=3.5)](https://travis-ci.org/json4s/json4s)

%package data
Summary: data components for the mvn-json4s package.
Group: Data

%description data
data components for the mvn-json4s package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-ast_2.12/3.5.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-ast_2.12/3.5.3/json4s-ast_2.12-3.5.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-ast_2.12/3.5.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-ast_2.12/3.5.3/json4s-ast_2.12-3.5.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-core_2.12/3.5.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-core_2.12/3.5.3/json4s-core_2.12-3.5.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-core_2.12/3.5.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-core_2.12/3.5.3/json4s-core_2.12-3.5.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-jackson_2.12/3.5.3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-jackson_2.12/3.5.3/json4s-jackson_2.12-3.5.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-jackson_2.12/3.5.3
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-jackson_2.12/3.5.3/json4s-jackson_2.12-3.5.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-scalap_2.12/3.5.3
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-scalap_2.12/3.5.3/json4s-scalap_2.12-3.5.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-scalap_2.12/3.5.3
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-scalap_2.12/3.5.3/json4s-scalap_2.12-3.5.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/json4s/json4s-ast_2.12/3.5.3/json4s-ast_2.12-3.5.3.jar
/usr/share/java/.m2/repository/org/json4s/json4s-ast_2.12/3.5.3/json4s-ast_2.12-3.5.3.pom
/usr/share/java/.m2/repository/org/json4s/json4s-core_2.12/3.5.3/json4s-core_2.12-3.5.3.jar
/usr/share/java/.m2/repository/org/json4s/json4s-core_2.12/3.5.3/json4s-core_2.12-3.5.3.pom
/usr/share/java/.m2/repository/org/json4s/json4s-jackson_2.12/3.5.3/json4s-jackson_2.12-3.5.3.jar
/usr/share/java/.m2/repository/org/json4s/json4s-jackson_2.12/3.5.3/json4s-jackson_2.12-3.5.3.pom
/usr/share/java/.m2/repository/org/json4s/json4s-scalap_2.12/3.5.3/json4s-scalap_2.12-3.5.3.jar
/usr/share/java/.m2/repository/org/json4s/json4s-scalap_2.12/3.5.3/json4s-scalap_2.12-3.5.3.pom
